services:
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: dataops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
